### ISSUE TITLE
More documentation needed

### ISSUE THREAD

**Issue by jizusun** [GilbertSun/vue-calendar#1]
For example 
- [x] screentshot,
- [x]  configuration, 
- [x] demo
- [ ] further clarification, e.g. for mobile only?

I think I need all these to judge my star :smile:

**Comment by GilbertSun** [comment]
this is a sun repo for bh-mint-ui, so all the document in bh-mint-ui

**Comment by GilbertSun** [comment]
https://wisedu.github.io/bh-mint-ui-docs/#!/zh-cn/calendar

**Comment by GilbertSun** [comment]
but this is a good idea to add own document and demo in repo

**Comment by jizusun** [comment]
why reopen...

**Comment by GilbertSun** [comment]
因为我确实要加文档，先开着，加完就关掉

**Comment by GilbertSun** [comment]
添加完毕
