### ISSUE TITLE
startMonday

### ISSUE THREAD

**Issue by xiaowoniu22** [GilbertSun/vue-calendar#2]
Thank you for your component. When I used it ,I found a weird question that "startMonday" always is true even though I  set default as false. But if I changed "startMon" or any word ,it would work successfully. I do not know why.
![qq 20170112230858](https://cloud.githubusercontent.com/assets/11738672/21895204/c6f99f94-d91c-11e6-871a-824aca6cd6bc.png)
![qq 20170112231324](https://cloud.githubusercontent.com/assets/11738672/21895214/cf6e535e-d91c-11e6-8d9b-287092d5317a.png)

**Comment by necfol** [comment]
how you use it by 'startMonday',i think , 
![image](https://cloud.githubusercontent.com/assets/8786120/21898288/5ab98db6-d927-11e6-9a50-118a7af2ab02.png)

**Comment by necfol** [comment]
<img width="1022" alt="2017-01-13 00 29 19" src="https://cloud.githubusercontent.com/assets/8786120/21898319/75fcb328-d927-11e6-873e-65b0a8b67103.png">
how you use 'startMonday'? I think you forgot that we had passed the values in the template.We've passed ':start-monday=true' on calendar-demo.vue

**Comment by necfol** [comment]
@xiaowoniu22

**Comment by GilbertSun** [comment]
@xiaowoniu22 is @necfol sloved your question?

**Comment by xiaowoniu22** [comment]
Yes, my question has been solved.Thanks.@necfol  and @GilbertSun.
